// GENERATED by pipeline/run.js — do not edit by hand.
// Generated 2026-08-10T11:39:12.679Z. 2 events.
// To correct a record, edit pipeline/data/events.json and add the field name to
// that record's "pinned" array so the crawler stops overwriting it.

(function(){
if (window.RIDE_EVENTS) return;

const P = {
  rollers: [0.2,0.35,0.22,0.44,0.28,0.5,0.32,0.55,0.38,0.6,0.42,0.58,0.35,0.52,0.3,0.48,0.34,0.56,0.4,0.62,0.45,0.58,0.38,0.5,0.32,0.46,0.28,0.4,0.24,0.34,0.2,0.26],
  bigclimb: [0.1,0.14,0.2,0.3,0.44,0.6,0.78,0.92,1,0.86,0.62,0.4,0.28,0.22,0.3,0.46,0.66,0.84,0.96,0.8,0.56,0.34,0.24,0.34,0.5,0.7,0.88,0.7,0.44,0.26,0.16,0.1],
  lumpy: [0.3,0.5,0.32,0.6,0.38,0.72,0.44,0.66,0.5,0.8,0.46,0.7,0.54,0.86,0.5,0.74,0.42,0.64,0.5,0.78,0.44,0.6,0.36,0.56,0.42,0.68,0.34,0.52,0.3,0.44,0.26,0.32],
  flat: [0.14,0.18,0.16,0.22,0.18,0.24,0.2,0.26,0.22,0.28,0.2,0.24,0.18,0.26,0.22,0.3,0.24,0.28,0.2,0.26,0.18,0.22,0.2,0.24,0.18,0.2,0.16,0.22,0.18,0.2,0.16,0.14],
  sawtooth: [0.2,0.6,0.25,0.7,0.3,0.8,0.35,0.9,0.4,0.75,0.3,0.85,0.4,0.95,0.45,0.8,0.35,0.9,0.5,1,0.55,0.85,0.4,0.7,0.45,0.8,0.35,0.6,0.3,0.5,0.25,0.35],
  mountain: [0.08,0.2,0.4,0.66,0.9,1,0.84,0.6,0.36,0.18,0.1,0.16,0.34,0.58,0.82,0.96,0.9,0.7,0.46,0.26,0.14,0.2,0.42,0.68,0.88,0.98,0.78,0.5,0.28,0.16,0.1,0.06],
  steady: [0.12,0.2,0.3,0.38,0.48,0.56,0.64,0.72,0.8,0.88,0.94,1,0.92,0.82,0.7,0.6,0.66,0.76,0.86,0.94,0.86,0.72,0.58,0.46,0.38,0.44,0.52,0.4,0.3,0.22,0.16,0.1],
};

window.RIDE_EVENTS = [
  { id:"tour-d-athens", name:"Tour d' Αθήνα", org:"Tour de Athens", date:"2026-09-05", city:"Athens", state:"TX", lat:32.205, lon:-95.855, type:"road-century", dist:[23,34,56,63], gain:2900, s:[100,0,0], cost:[40,50], deadline:"2026-08-16", support:4, aid:5, cutoff:"Rest stops and SAG close 4:00pm", lodging:"Athens TX motels; start/finish First United Methodist Church, 225 Lovers Ln", diff:2, url:"http://www.athensbikeride.com", verified:true, blurb:"Four routes on the backroads of East Texas, every one with a respectable amount of climbing. Packet pickup 5am, metric and 55-mile roll out 7:30am. Early-bird $40 through May 31, $45 in June–July, $50 from August. T-shirt guaranteed if registered by Aug 16.", prof:P.rollers },

  { id:"athens-to-savannah", name:"Athens to Savannah Ride", org:"Georgia Hi-Lo Trail", date:"2026-10-14", endDate:"2026-10-18", city:"Athens", state:"GA", lat:33.96, lon:-83.378, type:"gravel-fondo", dist:[285,307], gain:9800, s:[30,50,20], cost:[295,595], deadline:"2026-09-30", support:5, aid:14, cutoff:"Daily stage cutoffs, full SAG", lodging:"Camping at each stage finish or lodging partners in Greensboro, Sandersville, Statesboro, Savannah; return shuttle offered", diff:4, url:"https://www.athenstosavannah.com", verified:true, blurb:"Fundraiser for the 211-mile Georgia Hi-Lo Trail. Choose the 4-day gravel route (about 70% gravel and dirt, 30% connected pavement) or the 3-day road route, ride one day or all of them. Athens → White Plains → Tennille → Statesboro → Savannah.", prof:P.rollers },
];

window.RIDE_TYPES = {
  'gravel-race':   { label:'Gravel race',       short:'GRVL',  key:'A' },
  'gravel-fondo':  { label:'Gravel fondo',      short:'FONDO', key:'B' },
  'road-race':     { label:'Road race',         short:'ROAD',  key:'C' },
  'road-century':  { label:'Century / charity', short:'CENT',  key:'D' },
};
})();
