// Serialise the JSON store back into events.js — the file the site loads.
// The site's contract is: window.RIDE_EVENTS is an array whose `prof` is a
// reference into the shared profile table. Records past the review threshold
// are excluded so nothing unverified reaches the page — approve them with
// `node pipeline/approve.js` once you have eyeballed them.

import { CONFIDENCE_THRESHOLD } from './schema.js';

const SITE_FIELDS = ['id', 'name', 'org', 'date', 'endDate', 'city', 'state', 'lat', 'lon',
  'type', 'dist', 'gain', 's', 'cost', 'deadline', 'support', 'aid', 'cutoff',
  'lodging', 'diff', 'url', 'verified', 'blurb', 'img', 'tags'];

const j = (v) => JSON.stringify(v);

export function emit(store) {
  // Confidence scoring exists to hold back uncertain *crawled* records. Anything
  // a human entered by hand publishes regardless — the 33 seed events sit at 0.6
  // and applying the threshold to them would have silently emptied the site.
  // `approved: true` is the same escape hatch applied after the fact: a human
  // read the record and said yes, which outranks whatever the scorer thinks.
  const live = store.events.filter((e) =>
    !e.needsReview &&
    (e.approved === true ||
     String(e.source || '').startsWith('manual:') ||
     (e.confidence ?? 1) >= CONFIDENCE_THRESHOLD));

  const profiles = Object.entries(store.profiles)
    .map(([k, v]) => `  ${k}: [${v.join(',')}],`).join('\n');

  const records = live.map((e) => {
    const parts = SITE_FIELDS
      .filter((k) => e[k] !== undefined && e[k] !== null)
      .map((k) => `${k}:${j(e[k])}`);
    // `profile` is optional — emitting `prof:P.undefined` would hand the site a
    // key whose value is undefined, which is worse than the key being absent.
    if (e.profile && store.profiles[e.profile]) parts.push(`prof:P.${e.profile}`);
    return `  { ${parts.join(', ')} },`;
  }).join('\n\n');

  return `// GENERATED by pipeline/run.js — do not edit by hand.
// Generated ${store.generated}. ${live.length} events.
// To correct a record, edit pipeline/data/events.json and add the field name to
// that record's "pinned" array so the crawler stops overwriting it.

(function(){
if (window.RIDE_EVENTS) return;

const P = {
${profiles}
};

window.RIDE_EVENTS = [
${records}
];

// The footer's "Collated" date reads this. Emitted as a plain ISO string so the
// page formats it for its own locale rather than trusting the build machine's.
window.RIDE_GENERATED = ${j(store.generated)};

window.RIDE_TYPES = {
  'gravel-race':   { label:'Gravel race',       short:'GRVL',  key:'A' },
  'gravel-fondo':  { label:'Gravel fondo',      short:'FONDO', key:'B' },
  'road-race':     { label:'Road race',         short:'ROAD',  key:'C' },
  'road-century':  { label:'Century / charity', short:'CENT',  key:'D' },
};

// Gate classification. Absent tags means the event reads as a race.
window.RIDE_TAGS = {
  charity: { label:'Charity ride', short:'BENEFIT' },
  ride:    { label:'Untimed ride', short:'RIDE' },
};
})();
`;
}
