// Serialise the JSON store back into events.js — the file the site loads.
// The site's contract is: window.RIDE_EVENTS is an array whose `prof` is a
// reference into the shared profile table. Records past the review threshold
// are excluded so nothing unverified reaches the page.

import { CONFIDENCE_THRESHOLD } from './schema.js';

const SITE_FIELDS = ['id', 'name', 'org', 'date', 'endDate', 'city', 'state', 'lat', 'lon',
  'type', 'dist', 'gain', 's', 'cost', 'deadline', 'support', 'aid', 'cutoff',
  'lodging', 'diff', 'url', 'verified', 'blurb', 'img'];

const j = (v) => JSON.stringify(v);

export function emit(store) {
  const live = store.events.filter((e) => !e.needsReview && (e.confidence ?? 1) >= CONFIDENCE_THRESHOLD);

  const profiles = Object.entries(store.profiles)
    .map(([k, v]) => `  ${k}: [${v.join(',')}],`).join('\n');

  const records = live.map((e) => {
    const parts = SITE_FIELDS
      .filter((k) => e[k] !== undefined && e[k] !== null)
      .map((k) => `${k}:${j(e[k])}`);
    return `  { ${parts.join(', ')}, prof:P.${e.profile} },`;
  }).join('\n\n');

  return `// GENERATED by pipeline/run.js — do not edit by hand.
// Generated ${store.generated}. ${live.length} events.
// To correct a record, edit pipeline/data/events.json and add the field name to
// that record's "pinned" array so the crawler stops overwriting it.

(function(){
if (window.RIDE_EVENTS) return;

const P = {
${profiles}
};

window.RIDE_EVENTS = [
${records}
];

window.RIDE_TYPES = {
  'gravel-race':   { label:'Gravel race',       short:'GRVL',  key:'A' },
  'gravel-fondo':  { label:'Gravel fondo',      short:'FONDO', key:'B' },
  'road-race':     { label:'Road race',         short:'ROAD',  key:'C' },
  'road-century':  { label:'Century / charity', short:'CENT',  key:'D' },
};
})();
`;
}
